{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import threading\n",
    "from threading import Thread\n",
    "from time import sleep\n",
    "import sys\n",
    "import os\n",
    "import numpy as np\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/ARCGraph.py:860: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.\n",
      "  fig = plt.figure(figsize=(6, 6))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-24 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-19 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-82 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-89 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-91 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-125 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 2)\n",
      "Exception in thread Thread-128 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "Exception in thread Thread-127 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 6)\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 12)\n",
      "Exception in thread Thread-131 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-135 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "Exception in thread Thread-134 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 10)\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 11)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-132 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-164 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 308, in initialize_frontier\n",
      "    self.expand_frontier(frontier_node)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 505, in expand_frontier\n",
      "    apply_call_score, results_token = self.calculate_score(cumulated_apply_calls)\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 754, in calculate_score\n",
      "    token_string = token_string + str(reconstructed.graph.nodes[(r, c)][\"color\"])\n",
      "                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (3, 0)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-34 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-29 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-48 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-58 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-56 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n",
      "Exception in thread Thread-71 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n",
      "Exception in thread Thread-73 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-74 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n",
      "Exception in thread Thread-81 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n",
      "Exception in thread Thread-85 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n",
      "Exception in thread Thread-83 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n",
      "Exception in thread Thread-84 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-87 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n",
      "Exception in thread Thread-88 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "Exception in thread Thread-90 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 6)\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n",
      "Exception in thread Thread-92 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-86 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-111 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-130 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n",
      "Exception in thread Thread-126 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-129 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 7)\n",
      "Exception in thread Thread-133 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-155 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n",
      "Exception in thread Thread-163 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 308, in initialize_frontier\n",
      "    self.expand_frontier(frontier_node)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 505, in expand_frontier\n",
      "    apply_call_score, results_token = self.calculate_score(cumulated_apply_calls)\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 754, in calculate_score\n",
      "    token_string = token_string + str(reconstructed.graph.nodes[(r, c)][\"color\"])\n",
      "                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-167 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 308, in initialize_frontier\n",
      "    self.expand_frontier(frontier_node)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 505, in expand_frontier\n",
      "    apply_call_score, results_token = self.calculate_score(cumulated_apply_calls)\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 754, in calculate_score\n",
      "    token_string = token_string + str(reconstructed.graph.nodes[(r, c)][\"color\"])\n",
      "                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-174 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 5)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-157 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-94 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 785, in constraints_acquisition_global\n",
      "    if (data[\"color\"] != input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 4)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-170 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n",
      "Exception in thread Thread-172 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 3)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-169 (get_obj_representation):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 114, in get_obj_representation\n",
      "    stop_search = self.initialize_frontier()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 299, in initialize_frontier\n",
      "    self.constraints_acquisition_global()\n",
      "  File \"/Users/kartik/Desktop/arc/concept_arc/ARGA_AAAI23/task.py\", line 787, in constraints_acquisition_global\n",
      "    or (data[\"color\"] == input.background_color and self.train_output[i].graph.nodes[node][\n",
      "                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py\", line 194, in __getitem__\n",
      "    return self._nodes[n]\n",
      "           ~~~~~~~~~~~^^^\n",
      "KeyError: (0, 6)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n",
      "Done\n"
     ]
    }
   ],
   "source": [
    "sys.path.append(\"./ARGA_AAAI23\")\n",
    "from ARGA_AAAI23.task import Task\n",
    "\n",
    "root_path = \"./corpus\"\n",
    "X = []\n",
    "labels = []\n",
    "threads=[]\n",
    "for concept in os.listdir(root_path):\n",
    "    for task in os.listdir(os.path.join(root_path, concept)):\n",
    "        task_path = os.path.join(root_path, concept, task)\n",
    "        X.append(None)\n",
    "        labels.append(concept)\n",
    "        threads.append(None)\n",
    "\n",
    "        task = Task(task_path)\n",
    "\n",
    "        i = len(threads)-1\n",
    "        threads[i] = Thread(target=task.get_obj_representation, args=(True, 600, True, True, i, X))\n",
    "        threads[i].start()\n",
    "\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "root_path = \"./corpus\"\n",
    "labels = []\n",
    "for concept in os.listdir(root_path):\n",
    "    for task in os.listdir(os.path.join(root_path, concept)):\n",
    "        task_path = os.path.join(root_path, concept, task)\n",
    "        labels.append(concept)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "le = LabelEncoder()\n",
    "labels = le.fit_transform(labels)\n",
    "root_path = \"./object_based_corpus\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[10, 8, 11, 11, 8, 0, 11, 0, 8, 11, 9, 11, 9, 9, 7, 9]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "count = []\n",
    "for label in np.unique(labels):\n",
    "    label_name = le.inverse_transform([label])[0]\n",
    "    indexes = np.where(labels == label)[0]\n",
    "    os.makedirs(os.path.join(root_path, label_name))\n",
    "    count.append(0)\n",
    "    for idx in indexes:\n",
    "        task = {}\n",
    "        train = []\n",
    "        if X[idx] == None: continue\n",
    "        for i in range(len(X[idx][0])):\n",
    "            example = {}\n",
    "            example[\"input\"] = X[idx][0][i]\n",
    "            example[\"output\"] = X[idx][1][i]\n",
    "            train.append(example)\n",
    "\n",
    "        test = []\n",
    "        for i in range(len(X[idx][2])):\n",
    "            test_example = {}\n",
    "            test_example[\"input\"] = X[idx][2][i]\n",
    "            test_example[\"output\"] = X[idx][3][i]\n",
    "            test.append(test_example)\n",
    "\n",
    "        task[\"train\"] = train\n",
    "        task[\"test\"] = test\n",
    "\n",
    "        with open(os.path.join(root_path, label_name, f\"{idx}.json\"), 'w') as f:\n",
    "            json.dump(task, f)\n",
    "        \n",
    "        count[-1]+=1\n",
    "        \n",
    "count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "arc",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
